
replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "5.0"

enviromentVariables:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: rootpassword

service:
  type: NodePort
  port: 27017
  nodeport: 30017
  

affinity: {}