replicaCount: 1

image:
  repository: registry.gitlab.com/answerdigital/londonai/aide/workflow-manager-images/workflow-manager
  pullPolicy: IfNotPresent
  tag: 2022-07-25

imagePullSecrets:
 - name: gitlab-image-pull

enviromentVariables:
  WorkflowManager__storage__settings__endpoint: "minio:9000"
 # WorkflowManager__messaging__publisherSettings__endpoint: "rabbitmq"
 # WorkflowManager__messaging__subscriberSettings__endpoint: "rabbitmq"
  WorkflowManager__messaging__publisherSettings__endpoint: "rabbit-monai"
  WorkflowManager__messaging__subscriberSettings__endpoint: "rabbit-monai"
  WorkloadManagerDatabase__ConnectionString: "mongodb://root:rootpassword@mongo-service-monai:27017"

service:
  type: ClusterIP
  port: 5000




  
