# Default values for deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: progress
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

enviromentVariables:
  POSTGRES_PASSWORD: mysecretpassword
  
