name: Default

on:
  push:
    branches:
    - main
    - 'release/**'
  pull_request:
    branches:
    - main
    - 'release/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: |
        export VERSION=`cat VERSION`
        ./build.sh
        docker tag monai/workload-manager-core:$VERSION monai/workload-manager-core:${{ github.sha }}
        docker tag monai/orchestration-mediator:$VERSION monai/orchestration-mediator:${{ github.sha }}
    - name: Scan monai/workload-manager-core with Azure Container Scan
      uses: Azure/container-scan@v0
      with:
        image-name: monai/workload-manager-core:${{ github.sha }}
    - name: Scan monai/orchestration-mediator with Azure Container Scan
      uses: Azure/container-scan@v0
      with:
        image-name: monai/orchestration-mediator:${{ github.sha }}
    - name: Scan monai/workload-manager-core with Anchore
      id: scan-core
      uses: anchore/scan-action@v2
      with:
        image: monai/workload-manager-core:${{ github.sha }}
        fail-build: true
        severity-cutoff: high
        acs-report-enable: true
    - name: Scan monai/orchestration-mediator with Anchore
      id: scan-oms
      uses: anchore/scan-action@v2
      with:
        image: monai/orchestration-mediator:${{ github.sha }}
        fail-build: true
        severity-cutoff: high
        acs-report-enable: true
    # - name: upload Anchore scan SARIF report
    #   uses: github/codeql-action/upload-sarif@v1
    #   with:
    #     sarif_file: ${{ steps.scan.outputs.sarif }}

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run Unit Test
      run: ./run-tests.sh
      working-directory: ./src
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./src/results
        files: "**/coverage.opencover.xml"
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
