# SPDX-FileCopyrightText: © 2021-2022 MONAI Consortium
# SPDX-License-Identifier: Apache License 2.0

name: License Finder

on:
  push:
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: licensefinder/license_finder:7.0.1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Enable NuGet cache
      uses: actions/cache@v2.1.7
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Restore Solution
      run: dotnet restore Monai.Deploy.WorkflowManager.sln
      working-directory: ./src

    - name: Build Solution
      run: dotnet build -c Release --nologo --no-restore Monai.Deploy.WorkflowManager.sln
      working-directory: ./src

    - name: Perform License Scanning
      run: license_finder -r
      working-directory: ./src