# SPDX-FileCopyrightText: © 2021-2022 MONAI Consortium
# SPDX-License-Identifier: Apache License 2.0

name: Publish and scan

on:
  push:
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'
  # See https://github.com/goodwithtech/dockle/issues/188
  DOCKLE_HOST: "unix:///var/run/docker.sock"

jobs:
  publish-and-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build containers and publish
      run: |
        export VERSION=`cat VERSION`
        ./build.sh
        docker tag monai/workflow-manager:$VERSION monai/workflow-manager:${{ github.sha }}
  
    - name: Scan image with Azure Container Scan
      uses: Azure/container-scan@v0
      with:
        image-name: monai/workflow-manager:${{ github.sha }}

    - name: Scan image with Anchore
      id: scan
      uses: anchore/scan-action@v2
      with:
        image: monai/workflow-manager:${{ github.sha }}
        fail-build: true
        severity-cutoff: high
        acs-report-enable: true

    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
